"""2.5 Sample from a checkpoint -- turn a trained tiny GPT into text.

What this file does
-------------------
Loads a saved GPT checkpoint, encodes a prompt with the byte tokenizer, and
autoregressively samples more byte tokens. The generated byte IDs are decoded
back into a Python string at the end.

Where this fits in the Part 2 training pipeline
-----------------------------------------------
    [ model_best.pt / model_final.pt ]
              |
    [ prompt string -> byte IDs ]
              |
    [ GPT.generate(...) ]          <-- THIS FILE
              |
    [ generated IDs -> decoded text ] <-- THIS FILE

Connection to Part 1 and later parts
------------------------------------
Part 1 explained one forward pass through attention. Sampling repeats that
forward pass one new token at a time. Later SFT/RLHF parts use the same
autoregressive generation loop, but with instruction prompts and reward-guided
policies.

Math
----
At each generation step:
    logits = GPT(context)[:, -1, :]
    logits = logits / temperature
    logits = top_k_top_p_filtering(logits)
    next_id ~ Categorical(softmax(logits))
    context = concat(context, next_id)

Shapes
------
    prompt_ids: LongTensor [1, prompt_len]
    out:        LongTensor [1, prompt_len + generated_len]

Visualization
-------------
See notebook section 2.5 -- Sampling. It visualizes the probability-filtering
step before multinomial sampling chooses the next byte.
"""

from __future__ import annotations
import argparse, torch
from tokenizer import ByteTokenizer
from model_gpt import GPT


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--ckpt', type=str, required=True)
    p.add_argument('--prompt', type=str, default='')
    p.add_argument('--tokens', type=int, default=200)
    p.add_argument('--temperature', type=float, default=1.0)
    p.add_argument('--top_k', type=int, default=50)
    p.add_argument('--top_p', type=float, default=None)
    p.add_argument('--cpu', action='store_true')
    args = p.parse_args()

    device = torch.device('cuda' if torch.cuda.is_available() and not args.cpu else 'cpu')

    tok = ByteTokenizer()
    prompt_ids = tok.encode(args.prompt).unsqueeze(0).to(device)
    if prompt_ids.numel() == 0:
        # If no prompt provided, seed with newline byte (10)
        prompt_ids = torch.tensor([[10]], dtype=torch.long, device=device)


    ckpt = torch.load(args.ckpt, map_location=device)
    config = ckpt.get('config', None)

    if config is None:
        # fall back to defaults
        model = GPT(tok.vocab_size, block_size=256).to(device)
        model.load_state_dict(ckpt['model'])
    else:
        model = GPT(**config).to(device)
        model.load_state_dict(ckpt['model'])

    with torch.no_grad():
        out = model.generate(prompt_ids, max_new_tokens=args.tokens, temperature=args.temperature, top_k=args.top_k, top_p=args.top_p)
    print(tok.decode(out[0].cpu()))


if __name__ == '__main__':
    main()
